// Generated by CoffeeScript 1.9.0
(function() {
  angular.module('helpscout-dashboard', []).controller('main', [
    '$scope', '$http', '$interval', function($scope, $http, $interval) {
      var HELPSCOUT_API_KEY, add_mailbox_listener, get_request_headers;
      HELPSCOUT_API_KEY = null;
      $scope.mailboxes = {};
      $http.get('api_key.php').success(function(data) {
        HELPSCOUT_API_KEY = data;
        if (data !== '') {
          $scope.hide_it = true;
          return $scope.init();
        }
      });
      get_request_headers = function() {
        return {
          'Authorization': 'Basic ' + Base64.encode(HELPSCOUT_API_KEY + ':X'),
          'Content-Type': 'application/x-www-form-urlencoded'
        };
      };
      $scope.init = function() {
        return $http.get('https://api.helpscout.net/v1/mailboxes.json', {
          headers: get_request_headers()
        }).success(function(mailboxes) {
          var item, mailbox_id, _i, _len, _ref, _results;
          $scope.api_ready = true;
          _ref = data.items;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            item = _ref[_i];
            mailbox_id = String(item.id);
            $scope.mailboxes[mailbox_id] = {
              id: mailbox_id,
              name: item.name,
              email: item.email,
              active_tickets: null,
              pending_tickets: null,
              folders: [],
              get_count: function(status) {
                return this.folders.reduce(function(folder, sum) {
                  if (folder.type === 'mytickets' || folder.type === 'open') {
                    return folder[status + 'Count'] + sum;
                  } else {
                    return sum;
                  }
                });
              }
            };
            _results.push(add_mailbox_listener(mailbox_id));
          }
          return _results;
        });
      };
      return add_mailbox_listener = function(mailbox_id) {
        var success_callback;
        success_callback = function(data) {
          var folder, idx, _i, _len, _ref;
          $scope.mailboxes[mailbox_id].color = 'white';
          $scope.mailboxes[mailbox_id].active_tickets_last = $scope.mailboxes[mailbox_id].active_tickets;
          $scope.mailboxes[mailbox_id].pending_tickets_last = $scope.mailboxes[mailbox_id].pending_tickets;
          _ref = data.item.folders;
          for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
            folder = _ref[idx];
            $scope.mailboxes[mailbox_id].folders[idx] = folder;
          }
          $scope.mailboxes[mailbox_id].active_tickets = $scope.mailboxes[mailbox_id].get_count('active', $scope.mailboxes[mailbox_id]);
          $scope.mailboxes[mailbox_id].total_tickets = $scope.mailboxes[mailbox_id].get_count('total', $scope.mailboxes[mailbox_id]);
          if ($scope.mailboxes[mailbox_id].active_tickets > $scope.mailboxes[mailbox_id].active_tickets_last) {
            return $scope.mailboxes[mailbox_id].color = 'lightseagreen';
          } else if ($scope.mailboxes[mailbox_id].active_tickets < $scope.mailboxes[mailbox_id].active_tickets_last) {
            return $scope.mailboxes[mailbox_id].color = 'lightgreen';
          }
        };
        return $interval(function() {
          return $http.get('https://api.helpscout.net/v1/mailboxes/' + mailbox_id + '.json', {
            headers: get_request_headers()
          }).success(success_callback);
        }, 2000);
      };
    }
  ]);

  angular.element(document).ready(function() {
    return angular.bootstrap(document, ['helpscout-dashboard']);
  });

}).call(this);
