// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('helpscout-dashboard', []).controller('main', [
    '$scope', '$http', '$interval', function($scope, $http, $interval) {
      var api_auth, request_headers, scriptTag, wrapper;
      $scope.api_key = null;
      $scope.mailboxes = {};
      $scope.clefKey = 'f5141de0b960fbeba62a08aeeaed6b6e';
      $scope.url = 'http://test.robert.gg/helpscout-dashboard/login.php';
      scriptTag = document.createElement('script');
      scriptTag.setAttribute('class', 'clef-button');
      scriptTag.setAttribute('data-embed', 'true');
      scriptTag.setAttribute('data-style', 'flat');
      scriptTag.setAttribute('data-color', 'blue');
      scriptTag.setAttribute('type', 'text/javascript');
      scriptTag.setAttribute('src', 'https://clef.io/v3/clef.js');
      scriptTag.setAttribute('data-app-id', $scope.clefKey);
      scriptTag.setAttribute('data-redirect-url', $scope.url);
      wrapper = document.getElementById('Clef').appendChild(scriptTag);
      $http.get('api_key.php').success(function(data) {
        $scope.api_key = data;
        if (data !== '') {
          $scope.hide_it = true;
          return $scope.init();
        }
      });
      api_auth = function() {
        return 'Basic ' + Base64.encode($scope.api_key + ':X');
      };
      request_headers = function() {
        return {
          headers: {
            'Authorization': api_auth(),
            'Content-Type': 'application/x-www-form-urlencoded'
          }
        };
      };
      $scope.init = function() {
        return $http.get('https://api.helpscout.net/v1/mailboxes.json', {
          headers: {
            'Authorization': api_auth(),
            'Content-Type': 'application/x-www-form-urlencoded'
          }
        }).success($scope.mailbox_controller);
      };
      $scope.mailbox_controller = function(data) {
        var item, mailbox_id, _i, _len, _ref, _results;
        $scope.api_ready = true;
        _ref = data.items;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          item = _ref[_i];
          mailbox_id = String(item.id);
          $scope.mailboxes[mailbox_id] = {};
          $scope.mailboxes[mailbox_id].id = mailbox_id;
          $scope.mailboxes[mailbox_id].name = item.name;
          $scope.mailboxes[mailbox_id].email = item.email;
          $scope.mailboxes[mailbox_id].active_tickets = null;
          $scope.mailboxes[mailbox_id].pending_tickets = null;
          $scope.mailboxes[mailbox_id].folders = [];
          $scope.mailboxes[mailbox_id].get_count = function(status, obj) {
            var count, folder, _j, _len1, _ref1;
            count = null;
            _ref1 = obj.folders;
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              folder = _ref1[_j];
              if (folder.type === 'mytickets' || folder.type === 'open') {
                count = count + folder[status + 'Count'];
              }
            }
            return count;
          };
          _results.push($scope.add_mailbox_listener(mailbox_id));
        }
        return _results;
      };
      return $scope.add_mailbox_listener = function(mailbox_id) {
        var success_callback;
        success_callback = function(data) {
          var folder, idx, _i, _len, _ref;
          $scope.mailboxes[mailbox_id].color = 'white';
          $scope.mailboxes[mailbox_id].active_tickets_last = $scope.mailboxes[mailbox_id].active_tickets;
          $scope.mailboxes[mailbox_id].pending_tickets_last = $scope.mailboxes[mailbox_id].pending_tickets;
          _ref = data.item.folders;
          for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
            folder = _ref[idx];
            $scope.mailboxes[mailbox_id].folders[idx] = folder;
          }
          $scope.mailboxes[mailbox_id].active_tickets = $scope.mailboxes[mailbox_id].get_count('active', $scope.mailboxes[mailbox_id]);
          $scope.mailboxes[mailbox_id].total_tickets = $scope.mailboxes[mailbox_id].get_count('total', $scope.mailboxes[mailbox_id]);
          if ($scope.mailboxes[mailbox_id].active_tickets > $scope.mailboxes[mailbox_id].active_tickets_last) {
            return $scope.mailboxes[mailbox_id].color = 'lightseagreen';
          } else if ($scope.mailboxes[mailbox_id].active_tickets < $scope.mailboxes[mailbox_id].active_tickets_last) {
            return $scope.mailboxes[mailbox_id].color = 'lightgreen';
          }
        };
        return $interval(function() {
          return $http.get('https://api.helpscout.net/v1/mailboxes/' + mailbox_id + '.json', request_headers()).success(success_callback);
        }, 2000);
      };
    }
  ]);

  angular.element(document).ready(function() {
    return angular.bootstrap(document, ['helpscout-dashboard']);
  });

}).call(this);
